version: '3.7'
services:
  web:
    build: .
    init: true
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "8000:3000"
